//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadiantRFID.RaaS.DomainModel.DeviceStatusRepositoryService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeviceStatus", Namespace="http://www.radiantrfid.com/rms/")]
    [System.SerializableAttribute()]
    public partial class DeviceStatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RadiantRFID.RaaS.DomainModel.DeviceStatusRepositoryService.AntennaStatus[] AntennasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid DeviceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsPollingEnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> StatusTimeUtcField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RadiantRFID.RaaS.DomainModel.DeviceStatusRepositoryService.AntennaStatus[] Antennas {
            get {
                return this.AntennasField;
            }
            set {
                if ((object.ReferenceEquals(this.AntennasField, value) != true)) {
                    this.AntennasField = value;
                    this.RaisePropertyChanged("Antennas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid DeviceID {
            get {
                return this.DeviceIDField;
            }
            set {
                if ((this.DeviceIDField.Equals(value) != true)) {
                    this.DeviceIDField = value;
                    this.RaisePropertyChanged("DeviceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsOn {
            get {
                return this.IsOnField;
            }
            set {
                if ((this.IsOnField.Equals(value) != true)) {
                    this.IsOnField = value;
                    this.RaisePropertyChanged("IsOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsPollingEnabled {
            get {
                return this.IsPollingEnabledField;
            }
            set {
                if ((this.IsPollingEnabledField.Equals(value) != true)) {
                    this.IsPollingEnabledField = value;
                    this.RaisePropertyChanged("IsPollingEnabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> StatusTimeUtc {
            get {
                return this.StatusTimeUtcField;
            }
            set {
                if ((this.StatusTimeUtcField.Equals(value) != true)) {
                    this.StatusTimeUtcField = value;
                    this.RaisePropertyChanged("StatusTimeUtc");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AntennaStatus", Namespace="http://www.radiantrfid.com/rms/")]
    [System.SerializableAttribute()]
    public partial class AntennaStatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsOnField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Index {
            get {
                return this.IndexField;
            }
            set {
                if ((this.IndexField.Equals(value) != true)) {
                    this.IndexField = value;
                    this.RaisePropertyChanged("Index");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsOn {
            get {
                return this.IsOnField;
            }
            set {
                if ((this.IsOnField.Equals(value) != true)) {
                    this.IsOnField = value;
                    this.RaisePropertyChanged("IsOn");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.radiantrfid.com/rms/", ConfigurationName="DeviceStatusRepositoryService.DeviceStatusRepository")]
    public interface DeviceStatusRepository {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radiantrfid.com/rms/DeviceStatusRepository/GetDeviceStatuses", ReplyAction="http://www.radiantrfid.com/rms/DeviceStatusRepository/GetDeviceStatusesResponse")]
        RadiantRFID.RaaS.DomainModel.DeviceStatusRepositoryService.DeviceStatus[] GetDeviceStatuses();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DeviceStatusRepositoryChannel : RadiantRFID.RaaS.DomainModel.DeviceStatusRepositoryService.DeviceStatusRepository, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DeviceStatusRepositoryClient : System.ServiceModel.ClientBase<RadiantRFID.RaaS.DomainModel.DeviceStatusRepositoryService.DeviceStatusRepository>, RadiantRFID.RaaS.DomainModel.DeviceStatusRepositoryService.DeviceStatusRepository {
        
        public DeviceStatusRepositoryClient() {
        }
        
        public DeviceStatusRepositoryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DeviceStatusRepositoryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeviceStatusRepositoryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeviceStatusRepositoryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RadiantRFID.RaaS.DomainModel.DeviceStatusRepositoryService.DeviceStatus[] GetDeviceStatuses() {
            return base.Channel.GetDeviceStatuses();
        }
    }
}
